# .github/workflows/pipeline.yml
name: cryptopipe-hourly

on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # 👇 Map your lowercase secrets to the DB_* env vars your code reads
    env:
      DB_HOST: ${{ secrets.host }}
      DB_NAME: ${{ secrets.dbname }}
      DB_USER: ${{ secrets.user }}
      DB_PASS: ${{ secrets.password }}
      DB_PORT: ${{ secrets.port }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r pipeline/requirements.txt

      - name: Ingest bronze
        run: python pipeline/ingest.py

      - name: Run transforms (silver & gold)
        run: python pipeline/run_etl.py

      - name: Generate forecast + insight
        run: python pipeline/generate_insight.py

      - name: Health check
        run: |
          python - <<'PY'
          import os, psycopg
            with psycopg.connect(user=os.environ["DB_USER"], password=os.environ["DB_PASS"], host=os.environ["DB_HOST"], port=int(os.environ.get("DB_PORT", "5432")), dbname=os.environ["DB_NAME"]) as conn:
              with conn.cursor() as cur:
                  cur.execute("select count(*) from gold_daily_metrics")
                  print("gold_daily_metrics rows:", cur.fetchone()[0])
                  cur.execute("select count(*) from insights")
                  print("insights rows:", cur.fetchone()[0])
          PY