# .github/workflows/pipeline.yml
name: cryptopipe-hourly

on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Map uppercase secrets -> lowercase env your code reads
    env:
      host:     ${{ secrets.DB_HOST }}
      dbname:   ${{ secrets.DB_NAME }}
      user:     ${{ secrets.DB_USER }}
      password: ${{ secrets.DB_PASS }}
      port:     ${{ secrets.DB_PORT }}
      SYMBOLS: BTC-USD,ETH-USD


    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r pipeline/requirements.txt

      - name: Show connection target (sanity check)
        run: |
          python - <<'PY'
          import os
          print("CONNECT TO:", os.getenv("host"), os.getenv("dbname"), os.getenv("user"), os.getenv("port"))
          missing = [k for k in ("host","dbname","user","port") if not os.getenv(k)]
          if missing: raise SystemExit(f"Missing envs: {missing}")
          PY

      - name: Ingest bronze
        run: python pipeline/ingest.py

      - name: Run transforms (silver & gold)
        run: python pipeline/run_etl.py

      - name: Generate forecast + insight
        run: python pipeline/generate_insight.py
